1706770540818	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1706771085710	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1706771085710	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1706771085711	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1706771085712	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1706771686491	Sync.Service	DEBUG	User-Agent: Firefox/122.0 (Linux x86_64) FxSync/1.124.0.20240123151424.desktop
1706771686491	Sync.Service	INFO	Starting sync at 2024-02-01 12:44:46 in browser session qfhROFySDeWx
1706771686491	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1706771686493	Sync.Status	INFO	Resetting Status.
1706771686493	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1706771686493	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1706771686493	FirefoxAccounts	DEBUG	getOAuthToken enter
1706771686494	FirefoxAccounts	TRACE	getCachedToken returning cached token
1706771686494	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1706771686494	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1706771686495	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1706771686495	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1706771686495	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/177970235/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1706771686495	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1706771686495	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1706771686495	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1706771686495	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1706771686497	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
