1704824023430	Sync.LogManager	DEBUG	Flushing file log
1704824023431	Sync.LogManager	DEBUG	Log cleanup threshold time: 1703960023431
1704824023432	Sync.LogManager	DEBUG	Done deleting files.
1704824048238	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1704824048398	Sync.SyncScheduler	DEBUG	Woke from sleep.
1704824048398	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1704824048398	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1704824048399	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1704824050399	Sync.Service	DEBUG	User-Agent: Firefox/121.0.1 (Linux x86_64) FxSync/1.123.0.20240109145044.desktop
1704824050399	Sync.Service	INFO	Starting sync at 2024-01-09 23:44:10 in browser session Br_4Chd2c4Yd
1704824050399	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1704824050401	Sync.Status	INFO	Resetting Status.
1704824050401	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1704824050401	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1704824050402	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/177970235/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1704824050403	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1704824050403	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1704824050403	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1704824050403	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1704824050404	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
